name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  reusable-ci:
    name: Reusable CI
    uses: ./.github/workflows/reusable-ci.yml
